---
title: "Precision projections of the delay of resistance mutations in non-small cell lung cancer via APOBEC3A/3B suppression"
author: "Orestis Nousias"
date: "09/13/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##CODE

library(cancereffectsizeR)
library(data.table)
library(dplyr)

#Download the data from the manuscript link Supplementary Table 7 that contains the calls for the patients and cell lines: https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-023-06303-1/MediaObjects/41586_2023_6303_MOESM7_ESM.txt 

# Define the URL of the file to download
file_url <- "https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-023-06303-1/MediaObjects/41586_2023_6303_MOESM7_ESM.txt"

# Define the destination file name
dest_file <- "Isozaki_et_al.calls.txt"

# Use download.file to fetch the file
download.file(file_url, dest_file, method="auto")

#Process the file to rename columns and retain only the data for the 24 patients
#Rename column names: name -> Unique_Patient_Identifier,	chr -> Chromosome,	pos -> Start_Position,	REF -> Reference_Allele,	ALT -> Tumor_Allele

# Step 1: Load the file
data <- read.table("Isozaki_et_al.calls.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE, skip = 3)

# Step 2: Rename the columns
data <- rename(data, Unique_Patient_Identifier = name, Chromosome = chr, Start_Position = pos, Reference_Allele = REF, Tumor_Allele = ALT)

# Step 3: Save the new file
write.table(data, "APOBEC_response_data.txt", sep = "\t", row.names = FALSE, quote = FALSE)

#Append the filtered file to the APOBEC_response_data.txt file with the patients and resistance mutations attributed to APOBEC (found in this github repository named filtered_mutations_processed.txt)
# Read the second file skipping the header
data <- read.delim("mutations_swanton.txt", skip=1, sep="\t")
write.table(data, "temp.txt", sep="\t", row.names=FALSE, quote=FALSE, col.names=FALSE)
file.append("APOBEC_response_data.txt", "temp.txt")
file.remove("temp.txt")

#Start running cancer effect size R
apobec_maf <- preload_maf(maf = fread("APOBEC_response_data.txt", sep = "\t"),
                           refset = "ces.refset.hg19")

#Create CESAnalysis and load data

cesa <- CESAnalysis(refset = "ces.refset.hg19")

cesa <- load_maf(cesa = cesa, maf = apobec_maf, maf_name = "APOBEC")

#CESA WITH Lung signatures

nsclc_exclusions <- suggest_cosmic_signature_exclusions(cancer_type = "Lung-AdenoCA", treatment_naive = NULL)

cesa <- trinuc_mutation_rates(
    cesa = cesa,
    signature_set = ces.refset.hg19$signatures$COSMIC_v3.2,
    signature_exclusions = nsclc_exclusions
)

#CONTINUE WITH GENE RATES

#print(ces.refset.hg19$covariates)

cesa <- gene_mutation_rates(cesa, covariates = ces.refset.hg19$covariates$lung)

#Get mutation rates per variant for the patients of interest

#all patients
samples_to_check <- c("MGH808-A", "MGH808-E", "MGH808-F", "MGH953-1", "MGH953-2-CL", "MGH953-3-CL", "MGH953-4-CL", "MGH953-6", "MGH10032-AS-mediastinal", "MGH10032-LL-supraclavicular-LN", "MGH10032-R-hilar-LN", "MGH10032-R-paratracheal-LN", "MGH10032-RLL", "MGH10032-pre-treatment", "MGH086-0", "MGH086-00", "MGH086-000", "MGH086-1", "MGH086-2", "MGH086-3", "MGH086-4", "MGH086-5", "MGH987-0", "MGH987-1", "MGH987-2", "AZ03SURG", "AZ09SURG", "AZ05SURG", "AZ10SURG", "TH067_E7", "TH019E5", "TH079E2", "TH087E5", "TH108E3", "TH11_post_2", 
"TH122E3", "TH153E3", "TH171_E3", "TH239E4", "TH287E2", "TH29_Post", "TH51_A2", "TH52_C_post", "TH74_2", "TH016E3", "TH169E6")

#Variant id's and corresponding change in the gene
#variant_id	gene_change
#2:29443610_C>T	ALK_D1203N
#2:29443589_C>T	ALK_E1210K
#2:29443613_C>T	ALK_G1202R
#2:29432682_C>G	ALK_G1269A
#2:29445469_G>C	ALK_L1122V
#2:29443631_G>T	ALK_L1196M
#2:29443600_G>C	ALK_S1206C
#7:55249092_G>C	EGFR_C797S
#7:55249071_C>T	EGFR_T790M
#2:29448369_G>A	ALK_L1044F
#2:29445213_A>T	ALK_I1171N
#2:29443625_G>A ALK_L1198F
#7:55259515_T>G EGFR_L858R

#X:47041439_C>T RBM10_Q595*
#5:133534894_C>G PPP2CA_G247A
#5:133537547_C>T PPP2CA_D160N
#5:133537621_C>G PPP2CA_R135T
#5:133541647_G>A PPP2CA_S93L
#5:133541797_G>A PPP2CA_S43F
#19:1455206_C>T APC2_Q158*
#3:178936091_G>A PIK3CA_E545K
#3:178936082_G>A PIK3CA_E542K
#17:38787032_C>T SMARCE1_E321K
#3:41266113_C>G CTNNB1_S37C
#8:26221270_C>A PPP2R2A_S289* # Found in cesa@maf 
#9:21974792_G>T CDKN2A.p16INK4a_S12* # Found in cesa@maf

variants_to_check <- c("2:29443610_C>T", "2:29443589_C>T", "2:29443613_C>T", "2:29432682_C>G", "2:29445469_G>C", "2:29443631_G>T", "2:29443600_G>C", "7:55249092_G>C", "7:55249071_C>T", "2:29448369_G>A", "2:29445213_A>T","2:29443625_G>A","7:55259515_T>G", "X:47041439_C>T", "5:133534894_C>G", "5:133537547_C>T", "5:133537621_C>G", "5:133541647_G>A", "5:133541797_G>A", "3:178936082_G>A", "17:38787032_C>T", "3:41266113_C>G", "8:26221270_C>A", "9:21974792_G>T")

# Generate the output using the baseline_mutation_rates function
output <- baseline_mutation_rates(cesa = cesa, variant_ids = variants_to_check, samples = samples_to_check)

write.table(output, file="Mutation_rates_per_variant.tsv", sep="\t", quote=FALSE, row.names=FALSE)

# Load the data
rename <- fread("Mutation_rates_per_variant.tsv") # Replace with your actual file path

# Create the mapping from variant IDs to gene names
name_mapping <- setNames(
    c("ALK_D1203N", "ALK_E1210K", "ALK_G1202R", "ALK_G1269A", 
      "ALK_L1122V", "ALK_L1196M", "ALK_S1206C", "EGFR_C797S", 
      "EGFR_T790M", "ALK_L1044F", "ALK_I1171N", "ALK_L1198F", 
      "EGFR_L858R", "RBM10_Q595*", "PPP2CA_G247A", "PPP2CA_D160N", 
      "PPP2CA_R135T", "PPP2CA_S93L", "PPP2CA_S43F", "APC2_Q158*", 
      "PIK3CA_E545K", "PIK3CA_E542K", "SMARCE1_E321K", "CTNNB1_S37C", 
      "PPP2R2A_S289*", "CDKN2A.p16INK4a_S12*"),
    c("2:29443610_C>T", "2:29443589_C>T", "2:29443613_C>T", "2:29432682_C>G", "2:29445469_G>C", "2:29443631_G>T", "2:29443600_G>C", "7:55249092_G>C", "7:55249071_C>T", "2:29448369_G>A", "2:29445213_A>T", "2:29443625_G>A", "7:55259515_T>G", "X:47041439_C>T", "5:133534894_C>G", "5:133537547_C>T", "5:133537621_C>G", "5:133541647_G>A", "5:133541797_G>A", "19:1455206_C>T", "3:178936091_G>A", "3:178936082_G>A", "17:38787032_C>T", "3:41266113_C>G", "8:26221270_C>A", "9:21974792_G>T")
)



# Rename the columns based on the mapping
names(rename) <- sapply(names(output), function(x) ifelse(x %in% names(name_mapping), name_mapping[x], x))

# Write the modified data frame back to a TSV file
fwrite(rename, file="Mutation_rates_per_variant_named.tsv", sep="\t", quote=FALSE)

file.remove("Mutation_rates_per_variant.tsv")

_____________________________________________________________________________
_____________________________________________________________________________

#Get the signature contributions for these variants

# Assuming you have defined 'samples_to_check' and 'variants_to_check' earlier
# Extract signature data
signature_data <- cesa@trinucleotide_mutation_weights$signature_weight_table

# Merge with MAF data
merged_data <- merge(cesa@maf, signature_data, by = "Unique_Patient_Identifier")

# Filter for specific variants and sample IDs
filtered_data <- merged_data[merged_data$variant_id %in% variants_to_check & 
                             merged_data$Unique_Patient_Identifier %in% samples_to_check, ]

# Convert the list-type 'genes' column to a character column
filtered_data$genes <- sapply(filtered_data$genes, function(x) ifelse(length(x) > 0, toString(x), NA))

# Write the filtered data to a TSV file, this file contains more data than we need, but it serves as an additional reference point
write.table(filtered_data, file = "filtered_data.tsv", sep = "\t", row.names = FALSE)

# Read the TSV file into a data frame
filtered_data <- fread("filtered_data.tsv")

# Define the columns to remove
columns_to_remove <- c("Chromosome", "Start_Position", "Reference_Allele", "Tumor_Allele",
                       "variant_type", "variant_id", "genes", "top_gene", "total_snvs", 
                       "sig_extraction_snvs", "group_avg_blended")

# Remove the specified columns
filtered_data <- filtered_data[, !names(filtered_data) %in% columns_to_remove, with = FALSE]

# Remove columns that only contain 0s
filtered_data <- filtered_data[, sapply(filtered_data, function(col) !all(col == 0)), with = FALSE]

# Move 'top_consequence' column to the first position and rename it to 'variant_id'
setnames(filtered_data, old = "top_consequence", new = "variant_id")
filtered_data <- filtered_data[, c("variant_id", setdiff(names(filtered_data), "variant_id")), with = FALSE]

# Write the modified data frame back to a TSV file
fwrite(filtered_data, file="Source_probabilities.tsv", sep="\t", quote=FALSE)


#Get the mutation rates for each variant in the Source probabilities file

# Read the datasets
mutation_rates <- fread("Mutation_rates_per_variant_named.tsv")
source_probabilities <- fread("Source_probabilities.tsv")

# Melt the mutation_rates data.table from wide to long format
mutation_rates_long <- melt(mutation_rates, id.vars = "Unique_Patient_Identifier", 
                            variable.name = "variant_id", value.name = "VAR_MUTRATE")

# Merge the long format mutation_rates with source_probabilities on 'variant_id'
source_probabilities <- merge(source_probabilities, mutation_rates_long, 
                              by = c("variant_id", "Unique_Patient_Identifier"), all.x = TRUE)

# Write the updated source_probabilities to a new TSV file
fwrite(source_probabilities, file="Source_probabilities_with_mutrates.tsv", sep="\t", quote=FALSE)

_________________________________________________________________________
_________________________________________________________________________

#Hypothetical Source Probabilities

# Assuming cesa@maf is a data frame with a column 'variant_id' and cesa@maf$genes is a list of genes

#Jeff Mandel-Hypothetical_Source_Probabilities

# Input the CESAnalysis, the sample ID (Unique_Patient_Identifier), and the variant ID.
# Replace the signature definitions if you didn't use COSMIC v3.2. (at the hypotheticalSourceProbFunction.R)

#source it 
source("hypotheticalSourceProbFunction.R")


#then run this loop for these ids:

# Define the variant IDs
variants_ids <- c("2:29443610_C>T", "2:29443589_C>T", "2:29443613_C>T", "2:29432682_C>G", "2:29445469_G>C", "2:29443631_G>T", "2:29443600_G>C", "7:55249092_G>C", "7:55249071_C>T", "2:29448369_G>A", "2:29445213_A>T","2:29443625_G>A","7:55259515_T>G", "X:47041439_C>T", "5:133534894_C>G", "5:133537547_C>T", "5:133537621_C>G", "5:133541647_G>A", "5:133541797_G>A", "3:178936082_G>A", "17:38787032_C>T", "3:41266113_C>G", "8:26221270_C>A", "9:21974792_G>T")

# Define the UPIs
#upis <- c("MGH086-1", "MGH086-3", "MGH086-00", "MGH086-2", "MGH086-4", "MGH086-5", "MGH086-0", "MGH086-000")

#Use the upis of the other four patients to produce the same file and change the file name output at the end of this block to the correct patient identifier because

#upis <- c("MGH808-A", "MGH808-E", "MGH808-F")

#upis <- c("MGH953-1", "MGH953-2-CL", "MGH953-3-CL", "MGH953-4-CL", "MGH953-6")

#upis <- c("MGH10032-AS-mediastinal", "MGH10032-LL-supraclavicular-LN", "MGH10032-R-hilar-LN", "MGH10032-R-paratracheal-LN", "MGH10032-RLL", "MGH10032-pre-treatment")

#upis <- c("MGH987-0", "MGH987-1", "MGH987-2")

#upis <- c("TH067_E7")
#upis <- c("TH171_E3")
#upis <- c("TH019E5")
#upis <- c("TH29_Post")
#upis <- c("TH287E2")
#upis <- c("TH016E3")
#upis <- c("TH079E2")
#upis <- c("TH108E3")
#upis <- c("TH11_post_2")
#upis <- c("TH122E3")
#upis <- c("TH153E3")
#upis <- c("TH52_C_post")
#upis <- c("TH74_2")
#upis <- c("TH51_A2")
#upis <- c("AZ03SURG")
#upis <- c("AZ05SURG")


# Define the variant IDs and UPIs (as before)

# Initialize an empty data frame to store the results
results_df <- data.frame()

# Nested loop over variant IDs and UPIs (as before)
for (variant_id in variants_ids) {
  for (upi in upis) {
    # Call the hypothetical_source_prob function
    result <- hypothetical_source_prob(cesa, upi, variant_id)
    
    # Append the result to the data frame
    results_df <- rbind(results_df, result)
  }
}

# Write the results to a TSV file
write.table(results_df, file = "temp.tsv", sep = "\t", row.names = FALSE, quote = FALSE)

# Read the TSV file into a data frame
hyp_prob <- fread("temp.tsv")

# Create the mapping from variant IDs to gene names
name_mapping <- setNames(
    c("ALK_D1203N", "ALK_E1210K", "ALK_G1202R", "ALK_G1269A", 
      "ALK_L1122V", "ALK_L1196M", "ALK_S1206C", "EGFR_C797S", 
      "EGFR_T790M", "ALK_L1044F", "ALK_I1171N", "ALK_L1198F", 
      "EGFR_L858R", "RBM10_Q595*", "PPP2CA_G247A", "PPP2CA_D160N", 
      "PPP2CA_R135T", "PPP2CA_S93L", "PPP2CA_S43F", "APC2_Q158*", 
      "PIK3CA_E545K", "PIK3CA_E542K", "SMARCE1_E321K", "CTNNB1_S37C", 
      "PPP2R2A_S289*", "CDKN2A.p16INK4a_S12*"),
    c("2:29443610_C>T", "2:29443589_C>T", "2:29443613_C>T", "2:29432682_C>G", "2:29445469_G>C", "2:29443631_G>T", "2:29443600_G>C", "7:55249092_G>C", "7:55249071_C>T", "2:29448369_G>A", "2:29445213_A>T", "2:29443625_G>A", "7:55259515_T>G", "X:47041439_C>T", "5:133534894_C>G", "5:133537547_C>T", "5:133537621_C>G", "5:133541647_G>A", "5:133541797_G>A", "19:1455206_C>T", "3:178936091_G>A", "3:178936082_G>A", "17:38787032_C>T", "3:41266113_C>G", "8:26221270_C>A", "9:21974792_G>T")
)
                           
# Ensure 'hyp_prob' is a data.table
setDT(hyp_prob)

# Rename the first column to 'variant_id' if it's not already named
setnames(hyp_prob, old = names(hyp_prob)[1], new = "variant_id")

# Use the name_mapping vector to replace the variant_id with gene names
hyp_prob[, variant_id := name_mapping[variant_id]]

# Now read the mutation rates data
mutation_rates <- fread("Mutation_rates_per_variant_named.tsv")

# Reshape mutation_rates from wide to long format
long_mutation_rates <- melt(mutation_rates, id.vars = "Unique_Patient_Identifier", 
                            variable.name = "variant_id", value.name = "VAR_MUTRATE")

# Merge hyp_prob with long_mutation_rates on 'Unique_Patient_Identifier' and 'variant_id'
merged_data <- merge(hyp_prob, long_mutation_rates, by = c("Unique_Patient_Identifier", "variant_id"), all.x = TRUE)


# Remove columns that contain only zero
merged_data <- merged_data[, sapply(merged_data, function(col) !all(col == 0)), with = FALSE]

# Move 'variant_id' column to the first position
setcolorder(merged_data, c("variant_id", setdiff(names(merged_data), "variant_id")))

# Write the merged data to a new TSV file
fwrite(merged_data, file="hyp_prob_AZ05SURG_mutrates.tsv", sep="\t", quote=FALSE)

file.remove("temp.tsv")

# results now contains the hypothetical probabilities for each variant and UPI combination and the variant mutation rates


______________________________________________________________________________
______________________________________________________________________________

#Figure 1 code

#First create the file Figure1.tsv

# Step 1: Rename a new df Figure1 <- source_probabilities #assuming the data frame source_probabilities is stil existing in the global env
Figure1 <- source_probabilities

# Step 2: Concatenate the first 2 columns of the Figure1 df with a "_" between and name the new column Unique_Patient_Identifier
Figure1$Unique_Patient_Identifier <- paste(Figure1[[1]], Figure1[[2]], sep = "_")

# Explicitly remove the "variant_id" column if it exists
Figure1 <- subset(Figure1, select = -c(variant_id))

# Prepare the custom order of IDs for Unique_Patient_Identifier

ordered_ids <- c(
  "ALK_S1206C_MGH086-0",
  "ALK_L1122V_MGH086-2",
  "ALK_G1269A_MGH086-5",
  "ALK_D1203N_MGH086-1",
  "ALK_E1210K_MGH086-1",
  "ALK_E1210K_TH171_E3",
  "ALK_G1202R_MGH953-6",
  "ALK_L1196M_MGH953-6",
  "EGFR_L858R_AZ03SURG",
  "RBM10_Q595*_AZ03SURG",
  "PPP2CA_D160N_TH067_E7",
  "PPP2CA_G247A_TH067_E7",
  "PPP2CA_R135T_TH067_E7",
  "PPP2CA_S43F_TH067_E7",
  "PPP2CA_S93L_TH067_E7",
  "EGFR_L858R_TH51_A2",
  "PPP2R2A_S289*_TH51_A2",
  "CDKN2A.p16INK4a_S12*_TH287E2",
  "EGFR_L858R_TH287E2",
  "EGFR_T790M_TH287E2",
  "PIK3CA_E542K_TH287E2",
  "ALK_G1269A_TH019E5",
  "SMARCE1_E321K_TH29_Post",
  "ALK_I1171N_MGH987-1",
  "ALK_L1198F_MGH987-2",
  "EGFR_T790M_TH74_2",
  "CTNNB1_S37C_TH016E3",
  "EGFR_T790M_TH016E3",
  "EGFR_L858R_AZ05SURG",
  "EGFR_C797S_MGH808-F",
  "EGFR_L858R_MGH808-F",
  "EGFR_T790M_MGH808-F",
  "EGFR_T790M_TH153E3",
  "EGFR_T790M_TH11_post_2",
  "EGFR_T790M_TH079E2",
  "EGFR_C797S_MGH10032-RLL",
  "EGFR_L858R_MGH10032-RLL",
  "EGFR_T790M_MGH10032-RLL",
  "EGFR_T790M_TH108E3",
  "EGFR_T790M_TH122E3",
  "EGFR_L858R_TH52_C_post",
  "EGFR_T790M_TH52_C_post"
)


# Step 3: Reorder the lines of the df using the custom order for Unique_Patient_Identifier
Figure1$Unique_Patient_Identifier <- factor(Figure1$Unique_Patient_Identifier, levels = ordered_ids)
Figure1 <- Figure1[order(Figure1$Unique_Patient_Identifier), ]

# Step 4: Save the df as Figure1.tsv, ensuring variant_id is excluded
write.table(Figure1, "Figure1.tsv", sep = "\t", row.names = FALSE, quote = FALSE, col.names = TRUE)



# Load libraries
library(tidyverse)
library(ggplot2)
library(dplyr)

# Load the data
#In processed data folder
data <- read.delim('Figure1.tsv', sep = '\t')

# do it with an ordered list instead
# Your ordered list of Unique Patient Identifiers
ordered_ids2 <- rev(c(
  "ALK_S1206C_MGH086-0",
  "ALK_L1122V_MGH086-2",
  "ALK_G1269A_MGH086-5",
  "ALK_D1203N_MGH086-1",
  "ALK_E1210K_MGH086-1",
  "ALK_E1210K_TH171_E3",
  "ALK_G1202R_MGH953-6",
  "ALK_L1196M_MGH953-6",
  "EGFR_L858R_AZ03SURG",
  "RBM10_Q595*_AZ03SURG",
  "PPP2CA_D160N_TH067_E7",
  "PPP2CA_G247A_TH067_E7",
  "PPP2CA_R135T_TH067_E7",
  "PPP2CA_S43F_TH067_E7",
  "PPP2CA_S93L_TH067_E7",
  "EGFR_L858R_TH51_A2",
  "PPP2R2A_S289*_TH51_A2",
  "CDKN2A.p16INK4a_S12*_TH287E2",
  "EGFR_L858R_TH287E2",
  "EGFR_T790M_TH287E2",
  "PIK3CA_E542K_TH287E2",
  "ALK_G1269A_TH019E5",
  "SMARCE1_E321K_TH29_Post",
  "ALK_I1171N_MGH987-1",
  "ALK_L1198F_MGH987-2",
  "EGFR_T790M_TH74_2",
  "CTNNB1_S37C_TH016E3",
  "EGFR_T790M_TH016E3",
  "EGFR_L858R_AZ05SURG",
  "EGFR_C797S_MGH808-F",
  "EGFR_L858R_MGH808-F",
  "EGFR_T790M_MGH808-F",
  "EGFR_T790M_TH153E3",
  "EGFR_T790M_TH11_post_2",
  "EGFR_T790M_TH079E2",
  "EGFR_C797S_MGH10032-RLL",
  "EGFR_L858R_MGH10032-RLL",
  "EGFR_T790M_MGH10032-RLL",
  "EGFR_T790M_TH108E3",
  "EGFR_T790M_TH122E3",
  "EGFR_L858R_TH52_C_post",
  "EGFR_T790M_TH52_C_post"
))


# Reshape the data into a long format
data_long <- data %>% pivot_longer(cols = -Unique_Patient_Identifier, 
                                   names_to = "signature", 
                                   values_to = "weight")

# Convert Unique_Patient_Identifier to a factor with the specified order
data_long$Unique_Patient_Identifier <- factor(data_long$Unique_Patient_Identifier, levels = ordered_ids2)

# Signature to process mapping
signature_process_mapping <- list(
  SBS1 = 'Deamination with age, clock-like (1)',
  SBS5 = 'Unknown, clock-like (5)',
  SBS13 = 'APOBEC (2,13)',
  SBS2 = 'APOBEC (2,13)',
  SBS3 = 'Defective homologous recombination (3)',
  SBS4 = 'Tobacco (4,29)',
  SBS7a = 'UV light (7a–d,38)',
  SBS7b = 'UV light (7a–d,38)',
  SBS7c = 'UV light (7a–d,38)',
  SBS7d = 'UV light (7a–d,38)',
  SBS38 = 'UV light (7a–d,38)',
  SBS11 = 'Prior treatment (11,31,32,35)',
  SBS22 = 'Mutagenic chemical exposure (22,24,42,88)',
  SBS24 = 'Mutagenic chemical exposure (22,24,42,88)',
  SBS42 = 'Mutagenic chemical exposure (22,24,42,88)',
  SBS88 = 'Mutagenic chemical exposure (22,24,42,88)',
  SBS16 = 'Alcohol-associated (16)',
  SBS29 = 'Tobacco (4,29)',
  SBS31 = 'Prior treatment (11,31,32,35)',
  SBS32 = 'Prior treatment (11,31,32,35)',
  SBS35 = 'Prior treatment (11,31,32,35)'
  # Add any additional signatures as needed
)

# Apply the mapping to the data
data_long$signature_process <- map_chr(data_long$signature, ~signature_process_mapping[[.]] %||% 'Non-actionable and unknown signatures')

#Aggregate the Weights: Then, aggregate the weights by Unique_Patient_Identifier and process.
#data_aggregated <- data_long %>%
#  group_by(Unique_Patient_Identifier, signature_process) %>%
#  summarise(weight = sum(weight))


# Filter out rows with weight = 0
data_long <- data_long %>% filter(weight > 0)

# Define the color palette
colors <- c(
  'APOBEC (2,13)' = '#8659a2',
  'Defective homologous recombination (3)' = '#ed0082',
  'Tobacco (4,29)' = '#a07627',
  'Unknown, clock-like (5)' = '#9d948d',
  'Deamination with age, clock-like (1)' = '#6a615c',
  'Non-actionable and unknown signatures' = 'black',
  'UV light (7a–d,38)' = '#ffffb3',
  'Prior treatment (11,31,32,35)' = '#80b1d3',
  'Mutagenic chemical exposure (22,24,42,88)' = '#fdb462',
  'Alcohol-associated (16)' = '#b3de69'
)

# Ensure the order of 'signature_process' matches the color vector
#data_long$signature_process <- factor(data_long$signature_process, levels = names(colors))
# Reverse the order of the levels of 'signature_process' to match the reversed 'colors' vector
data_long$signature_process <- factor(data_long$signature_process, levels = rev(names(colors)))

# Create and save the plots
unique_signature_processes <- unique(data_long$signature_process)

# Generate a single plot with all signature processes
p <- ggplot(data_long, aes(x = Unique_Patient_Identifier, y = weight, fill = signature_process)) +
    geom_bar(stat = "identity", color = "black", size = 0.75) + # Add black outline to bars
    scale_fill_manual(values = colors) + # Use predefined colors for each signature process
    labs(title = "Mutation Signature Processes", x = "Unique Patient Identifier", y = "Weight") +
    coord_flip() +
    theme_minimal() +
    theme(
        axis.text.x = element_text(color = "black"),  # X-axis text color
        axis.text.y = element_text(color = "black")   # Y-axis text color
    )

# Save the plot as PDF and PNG
ggsave("all_signature_processes_plot.pdf", plot = p, width = 10, height = 8, dpi = 300)
ggsave("all_signature_processes_plot.png", plot = p, width = 10, height = 7, dpi = 300)


_______________________________________________________________________________
_______________________________________________________________________________

#Time gained with R calculation

# Load necessary libraries
library(readr)

#Create the files for time gain calculation for the observed variants
# Step 1: Load the file
data <- read.table("Source_probabilities_with_mutrates.tsv", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# Step 2: Create the new columns
data <- data %>%
  mutate(
    SBS2_SBS13 = SBS2 + SBS13,
    APOBEC_RATE = `SBS2_SBS13` * VAR_MUTRATE,
    SUPRESSED_RATE = VAR_MUTRATE - APOBEC_RATE
  )

# Define the groups of patient identifiers
patient_groups <- list(
  MGH086 = c("MGH086-1", "MGH086-5", "MGH086-0", "MGH086-2"),
  MGH953 = c("MGH953-4-CL", "MGH953-6"),
  MGH10032 = c("MGH10032-RLL"),
  MGH808 = c("MGH808-F"),
  MGH987 = c("MGH987-1", "MGH987-2"),
  TH067_E7 = c("TH067_E7"),
  TH29_Post = c("TH29_Post"),
  TH171_E3 = c("TH171_E3"),
  TH016E3 = c("TH016E3"),
  TH079E2 = c("TH079E2"),
  TH108E3 = c("TH108E3"),
  TH11_post_2 = c("TH11_post_2"),
  TH122E3 = c("TH122E3"),
  TH153E3 = c("TH153E3"),
  TH287E2 = c("TH287E2"),
  TH52_C_post = c("TH52_C_post"),
  TH74_2 = c("TH74_2"),
  TH51_A2 = c("TH51_A2"),
  TH019E5 = c("TH019E5"),
  AZ03SURG = c("AZ03SURG"),
  AZ05SURG = c("AZ05SURG")
)



# Step 3: Split the file and save separate files
for (group_name in names(patient_groups)) {
  group_ids <- patient_groups[[group_name]]
  group_data <- filter(data, Unique_Patient_Identifier %in% group_ids)
  
  # Select only the necessary columns
  group_data <- group_data %>%
    select(Unique_Patient_Identifier, `SBS2_SBS13`, VAR_MUTRATE, APOBEC_RATE, SUPRESSED_RATE)
  
  # Write to a file
  write.table(group_data, paste0(group_name, "_time_calc.txt"), sep = "\t", row.names = FALSE, quote = FALSE)
}

____________________________________________________________________________

#Do the same for the MGH086 patient with the added variants (or for the other three patients)

# Step 1: Load the file
data <- read.table("hyp_prob_TH079E2_mutrates.tsv", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# Step 2: Create the new columns with valid variable names
data <- data %>%
  mutate(
    SBS2_SBS13 = SBS2 + SBS13,
    APOBEC_RATE = SBS2_SBS13 * VAR_MUTRATE,
    SUPRESSED_RATE = VAR_MUTRATE - APOBEC_RATE
  )

# Since all IDs are for MGH086, we don't need to split the data, just select the necessary columns
final_data <- data %>%
  select(Unique_Patient_Identifier, SBS2_SBS13, VAR_MUTRATE, APOBEC_RATE, SUPRESSED_RATE)

# Step 3: Save the data to a new file
write.table(final_data, "TH079E2_with_added_variants_time_calc.txt", sep = "\t", row.names = FALSE, quote = FALSE)

__________________________________________________________________________

#Calculation part equation 1

library(readr)

# Read the tab-delimited file (change the name each time and re-run the code)
data <- read_delim("MGH987_time_calc.txt", delim = "\t")

# Calculate the estimated time gained for each row
data$estimated_time_gained <- ((1 / data$SUPRESSED_RATE) - (1 / data$VAR_MUTRATE)) / (1 / data$VAR_MUTRATE) * 100

# Calculate the sum for all rows
sum_suppressed_rate <- sum(data$SUPRESSED_RATE, na.rm = TRUE)
sum_variant_rate <- sum(data$VAR_MUTRATE, na.rm = TRUE)
total_estimated_time_gained <- ((1 / sum_suppressed_rate) - (1 / sum_variant_rate)) / (1 / sum_variant_rate) * 100


# Output the results for each row
#write_csv(data, "Estimated_Time_Gained_Per_Row_MGH086_calc.csv")

# Print the total estimated time gained for all rows
print(paste("Total estimated time gained for all variants:", total_estimated_time_gained))

__________________________________________________________________________
#Simpler version of equation 1 code for time gained COMPARING Suppressed with Variant rates, change the file name each time

#TIME CALC FOR ALL LOOP

library(readr)
library(data.table)

# Initialize empty data frame to store results
results <- data.frame(
  Patient = character(),
  Type = character(),
  Measure = character(),
  Value = numeric(),
  stringsAsFactors = FALSE
)

# Get list of all time_calc.txt files
files <- list.files(pattern = ".*time_calc\\.txt$")

# Process each file
for(file in files) {
  # Extract patient ID from filename
  patient <- sub("_time_calc.txt", "", file)
  
  # Read data
  data <- read_delim(file, delim = "\t")
  
  # Calculate Ts and Tv
  Tv <- 1 / sum(data$VAR_MUTRATE, na.rm = TRUE)
  Ts <- 1 / sum(data$SUPRESSED_RATE, na.rm = TRUE)
  
  # Calculate time gained
  time_gained <- ((Ts / Tv) - 1) * 100
  
  # Type is "Observed" for regular files and "All Variants" for files with added variants
  type <- if(grepl("with_added_variants", file)) "All Variants" else "Observed"
  
  # Add results to data frame
  results <- rbind(results, 
                  data.frame(Patient = patient,
                            Type = type,
                            Measure = "Tv",
                            Value = Tv),
                  data.frame(Patient = patient,
                            Type = type,
                            Measure = "Ts",
                            Value = Ts),
                  data.frame(Patient = patient,
                            Type = type,
                            Measure = "TimeGained",
                            Value = time_gained))
}

# Write results to TSV file
write.table(results, 
            "time_calculations_summary.tsv", 
            sep = "\t", 
            row.names = FALSE, 
            quote = FALSE)

___________________________________________________________________

#Figure 2 code
#PLOTS FOR Ts and Tv

#Plot Tv (time without A3A suppressed) and Ts (time with A3A suppressed) for each patient for observed and with all variants

library(tibble)
library(ggplot2)
library(viridis)
library(dplyr)

# Creating the data frame
data <- tribble(
  ~Patient, ~Condition, ~Type, ~Value,
  "MGH086", "Observed", "Tv", 3484.55193253744,
  "MGH086", "Observed", "Ts", 49797.3594289553,
  "MGH086", "All Variants", "Tv", 399.56665533635,
  "MGH086", "All Variants", "Ts", 4770.71320012886,
  
  "MGH10032", "Observed", "Tv", 190515.310935723,
  "MGH10032", "Observed", "Ts", 190515.310935723,
  "MGH10032", "All Variants", "Tv", 1552.72689560694,
  "MGH10032", "All Variants", "Ts", 2223.97402964084,
  
  "MGH808", "Observed", "Tv", 50839.9789537358,
  "MGH808", "Observed", "Ts", 58484.880570656,
  "MGH808", "All Variants", "Tv", 2296.85610856521,
  "MGH808", "All Variants", "Ts", 6261.0806244645,
  
  "MGH953", "Observed", "Tv", 179172.311988901,
  "MGH953", "Observed", "Ts", 334288.988375356,
  "MGH953", "All Variants", "Tv", 949.036171596227,
  "MGH953", "All Variants", "Ts", 4537.31140954092,
  
  "MGH987", "Observed", "Tv", 452023.159675332,
  "MGH987", "Observed", "Ts", 562560.269136336,
  "MGH987", "All Variants", "Tv", 2044.30010291573,
  "MGH987", "All Variants", "Ts", 6112.76714472173,
  
  "TH016E3", "Observed", "Tv", 22377.0145497926,
  "TH016E3", "Observed", "Ts", 25891.773072281,
  "TH016E3", "All Variants", "Tv", 6246.5520424213,
  "TH016E3", "All Variants", "Ts", 13320.6545389594,
  
  "TH019E5", "Observed", "Tv", 216371.539633009,
  "TH019E5", "Observed", "Ts", 350674.103461681,
  "TH019E5", "All Variants", "Tv", 4354.35419898007,
  "TH019E5", "All Variants", "Ts", 21900.5358763377,
  
  "TH067_E7", "Observed", "Tv", 12969.4906191015,
  "TH067_E7", "Observed", "Ts", 27901.3859487074,
  "TH067_E7", "All Variants", "Tv", 3878.42419961271,
  "TH067_E7", "All Variants", "Ts", 31731.9546059496,
  
  "TH079E2", "Observed", "Tv", 64442.1255075542,
  "TH079E2", "Observed", "Ts", 67053.353226,
  "TH079E2", "All Variants", "Tv", 9912.66938273808,
  "TH079E2", "All Variants", "Ts", 13984.3828958546,
  
  "TH108E3", "Observed", "Tv", 41031.7547409628,
  "TH108E3", "Observed", "Ts", 41031.7547409628,
  "TH108E3", "All Variants", "Tv", 13017.9517554708,
  "TH108E3", "All Variants", "Ts", 13017.9517554708,
  
  "TH11_post_2", "Observed", "Tv", 44166.0625654178,
  "TH11_post_2", "Observed", "Ts", 48018.4728391516,
  "TH11_post_2", "All Variants", "Tv", 9823.37570482721,
  "TH11_post_2", "All Variants", "Ts", 13790.9812008152,
  
  "TH122E3", "Observed", "Tv", 23032.3052978959,
  "TH122E3", "Observed", "Ts", 23032.3052978959,
  "TH122E3", "All Variants", "Tv", 10902.1531752521,
  "TH122E3", "All Variants", "Ts", 10902.1531752521,
  
  "TH153E3", "Observed", "Tv", 38771.1811228807,
  "TH153E3", "Observed", "Ts", 43019.6006153571,
  "TH153E3", "All Variants", "Tv", 8306.65267346887,
  "TH153E3", "All Variants", "Ts", 14397.1637186327,
  
  "TH171_E3", "Observed", "Tv", 60149.3341556614,
  "TH171_E3", "Observed", "Ts", 170479.647156768,
  "TH171_E3", "All Variants", "Tv", 3557.59442510803,
  "TH171_E3", "All Variants", "Ts", 49443.9047179542,
  
  "TH287E2", "Observed", "Tv", 15954.7687450886,
  "TH287E2", "Observed", "Ts", 30169.402922303,
  "TH287E2", "All Variants", "Tv", 3738.89001257215,
  "TH287E2", "All Variants", "Ts", 27683.2228245804,
  
  "TH29_Post", "Observed", "Tv", 52537.2331164416,
  "TH29_Post", "Observed", "Ts", 73038.5673989592,
  "TH29_Post", "All Variants", "Tv", 5056.90970177957,
  "TH29_Post", "All Variants", "Ts", 19018.7875972962,
  
  "TH51_A2", "Observed", "Tv", 177642.677144107,
  "TH51_A2", "Observed", "Ts", 377069.730300683,
  "TH51_A2", "All Variants", "Tv", 3678.36672938424,
  "TH51_A2", "All Variants", "Ts", 30756.8345280698,
  
  "TH52_C_post", "Observed", "Tv", 42959.2517900127,
  "TH52_C_post", "Observed", "Ts", 42959.2517900127,
  "TH52_C_post", "All Variants", "Tv", 12295.1323570998,
  "TH52_C_post", "All Variants", "Ts", 12295.1323570998,
  
  "TH74_2", "Observed", "Tv", 85185.8698765271,
  "TH74_2", "Observed", "Ts", 99436.1863214514,
  "TH74_2", "All Variants", "Tv", 6887.85347458273,
  "TH74_2", "All Variants", "Ts", 14925.5489843388,
  
  "AZ03SURG", "Observed", "Tv", 512777.775125072,
  "AZ03SURG", "Observed", "Ts", 1167121.21501542,
  "AZ03SURG", "All Variants", "Tv", 3734.94510446597,
  "AZ03SURG", "All Variants", "Ts", 30917.269913185,
  
  "AZ05SURG", "Observed", "Tv", 1558981.27009151,
  "AZ05SURG", "Observed", "Ts", 1803505.78460035,
  "AZ05SURG", "All Variants", "Tv", 7003.49568105747,
  "AZ05SURG", "All Variants", "Ts", 14679.5067852137
)

# Add TimeGained data
time_gained_data <- tribble(
  ~Patient, ~Condition, ~TimeGained,
  "MGH086", "Observed", 1329.08931745187,
  "MGH086", "All Variants", 1093.97180330599,
  "MGH10032", "Observed", 0,
  "MGH10032", "All Variants", 43.2302123401759,
  "MGH808", "Observed", 15.0371848577612,
  "MGH808", "All Variants", 172.593507321434,
  "MGH953", "Observed", 86.5740217696491,
  "MGH953", "All Variants", 378.09678338281,
  "MGH987", "Observed", 24.453859740372,
  "MGH987", "All Variants", 199.015156140884,
  "TH016E3", "Observed", 15.7070037858152,
  "TH016E3", "All Variants", 113.248115896527,
  "TH019E5", "Observed", 62.070346246306,
  "TH019E5", "All Variants", 402.957152210253,
  "TH067_E7", "Observed", 115.130931261203,
  "TH067_E7", "All Variants", 718.16616679316,
  "TH079E2", "Observed", 4.05205088733411,
  "TH079E2", "All Variants", 41.0758530916707,
  "TH108E3", "Observed", 0,
  "TH108E3", "All Variants", 0,
  "TH11_post_2", "Observed", 8.72255766070995,
  "TH11_post_2", "All Variants", 40.3894304280587,
  "TH122E3", "Observed", 0,
  "TH122E3", "All Variants", 0,
  "TH153E3", "Observed", 10.9576736365383,
  "TH153E3", "All Variants", 73.320882485152,
  "TH171_E3", "Observed", 183.427322263587,
  "TH171_E3", "All Variants", 1289.81285694062,
  "TH287E2", "Observed", 89.0933262921167,
  "TH287E2", "All Variants", 640.412869367503,
  "TH29_Post", "Observed", 39.0224857047176,
  "TH29_Post", "All Variants", 276.095060400293,
  "TH51_A2", "Observed", 112.263030687608,
  "TH51_A2", "All Variants", 736.15465207349,
  "TH52_C_post", "Observed", 0,
  "TH52_C_post", "All Variants", 0,
  "TH74_2", "Observed", 16.7284978900603,
  "TH74_2", "All Variants", 116.693764456756,
  "AZ05SURG", "Observed", 15.6848911016418,
  "AZ05SURG", "All Variants", 109.602567827916,
  "AZ03SURG", "Observed", 127.607605405821,
  "AZ03SURG", "All Variants", 727.783783922725
)

# First join the time gained data with the normalized data
normalized_data <- data %>%
  group_by(Patient, Condition) %>%
  mutate(
    Normalized_Value = case_when(
      Type == "Ts" ~ 100,  # Set all Ts to 100%
      Type == "Tv" ~ (Value / Value[Type == "Ts"]) * 100  # Normalize Tv relative to Ts
    )
  ) %>%
  ungroup() %>%
  mutate(Type = factor(Type, 
                      levels = c("Ts", "Tv"),
                      labels = c("with APOBEC inhibited", "without APOBEC inhibited")))




# Create the plotting function with compact spacing and single time gained header
create_normalized_plot <- function(data, time_gained_data, condition_name) {
  tv_ratios <- data %>%
    filter(Condition == condition_name, Type == "without APOBEC inhibited") %>%
    arrange(desc(Normalized_Value)) %>%
    pull(Patient)
  
  filtered_data <- filter(data, Condition == condition_name) %>%
    mutate(Patient = factor(Patient, levels = tv_ratios))
  
  time_gained <- time_gained_data %>%
    filter(Condition == condition_name) %>%
    mutate(Patient = factor(Patient, levels = tv_ratios))
  
  max_x <- max(filtered_data$Normalized_Value) * 1.1
  
  ggplot(filtered_data, aes(x = Normalized_Value, y = Patient)) +
    geom_bar(aes(fill = Type), 
             stat = "identity", 
             position = "dodge",
             width = 0.6,
             color = "black") +
    geom_text(data = time_gained,
              aes(x = max_x,
                  label = sprintf("%.1f", TimeGained)),
              hjust = 0,
              size = 3,
              color = "black") +
    annotate("text", 
             x = max_x,
             y = length(tv_ratios) + 0.5,
             label = "Time gained (%)",
             hjust = 0,
             size = 3.5,
             fontface = "bold",
             color = "black") +
    # Add molecular clock annotation at the bottom
    annotate("text",
             x = max_x/2,  # Center of the plot
             y = 0,  # Bottom of the plot
             label = "Time (molecular clock)",
             fontface = "bold",
             size = 3,
             color = "black",
             vjust = -1.2) +  # Adjust vertical position
    scale_fill_manual(values = c("with APOBEC inhibited" = "black", 
                                "without APOBEC inhibited" = "#8659a2")) +
    theme_minimal() +
    theme(
      text = element_text(color = "black"),
      axis.text.y = element_text(size = 10, color = "black"),
      axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      panel.grid = element_blank(),
      panel.border = element_blank(),
      plot.title = element_text(hjust = 0, size = 12, color = "black"),
      legend.text = element_text(color = "black"),
      legend.title = element_text(color = "black"),
      plot.margin = margin(r = 80, l = 5, b = 20, t = 20)  # Increased bottom margin
    ) +
    labs(
      title = paste("Normalized Ts/Tv Ratio -", condition_name),
      y = "",
      x = "",
      fill = "Type"
    ) +
    coord_cartesian(clip = "off") +
    scale_y_discrete(expand = c(0.02, 0.02))
}

# Create both plots with time gained data
observed_plot <- create_normalized_plot(normalized_data, time_gained_data, "Observed")
all_variants_plot <- create_normalized_plot(normalized_data, time_gained_data, "All Variants")

# Save the plots
ggsave("observed_variants_normalized.pdf", observed_plot, width = 9, height = 7)
ggsave("all_variants_normalized.pdf", all_variants_plot, width = 9, height = 7)


_____________________________________________________________________





















































































































































































































































































#TEMP##TEMP##TEMP##TEMP##TEMP##TEMP##TEMP##TEMP##TEMP##TEMP##TEMP##TEMP
#UTILITY CODE

# Look at what's in the MAF data
print(head(cesa@maf))

# Check the variant IDs specifically
print(unique(cesa@maf$variant_id))

# Look at the structure of the cesa object
str(cesa)


# Get mutations from cesa@maf
variants_df <- cesa@maf[, c("variant_id", "top_consequence")]

# Function to search for gene and amino acid change
search_variants <- function(gene, aa_change) {
  matches <- variants_df[grepl(paste0(gene, "_", aa_change), variants_df$top_consequence, fixed=TRUE),]
  if(nrow(matches) > 0) {
    return(matches)
  }
  return(NULL)
}

# List of mutations to check (excluding the known ones)
genes_to_check <- list(
  "RBM10" = "Q595*",
  "PPP2CA" = c("G247A", "D160N", "R135T", "S93L", "S43F"),
  "APC2" = "Q158*",
  "PIK3CA" = c("E545K", "E542K"),
  "CDKN2A" = "S12*",
  "SMARCE1" = "E321K", 
  "PPP2R2A" = "S279*",
  "CTNNB1" = "S37C"
)

# Check each gene and mutation
for(gene in names(genes_to_check)) {
  mutations <- genes_to_check[[gene]]
  if(!is.vector(mutations)) mutations <- c(mutations)
  
  for(mutation in mutations) {
    found <- search_variants(gene, mutation)
    if(!is.null(found)) {
      print(paste("Found:", gene, mutation))
      print(found)
    } else {
      print(paste("Not found:", gene, mutation))
    }
  }
}






# Let's check for PPP2R2A and CDKN2A in different ways
# First in amino_acid_change table
ppp2r2a_mutations <- cesa@mutations$amino_acid_change[gene == "PPP2R2A",]
print("PPP2R2A mutations found:")
print(ppp2r2a_mutations)

cdkn2a_mutations <- cesa@mutations$amino_acid_change[gene == "CDKN2A",]
print("CDKN2A mutations found:")
print(cdkn2a_mutations)

# Let's also try checking variant_id patterns
variants_with_ppp2r2a <- cesa@maf[grepl("PPP2R2A", top_consequence, ignore.case=TRUE),]
print("Variants with PPP2R2A:")
print(variants_with_ppp2r2a)

variants_with_cdkn2a <- cesa@maf[grepl("CDKN2A", top_consequence, ignore.case=TRUE),]
print("Variants with CDKN2A:")
print(variants_with_cdkn2a)







# Get available samples from cesa
available_samples <- cesa@samples$Unique_Patient_Identifier

# Check which samples from our list are not in cesa
missing_samples <- setdiff(samples_to_check, available_samples)
print("Samples not found in cesa:")
print(missing_samples)

# Check which samples are present
present_samples <- intersect(samples_to_check, available_samples)
print("Samples found in cesa:")
print(present_samples)






#code verification

# Complete test script including both calculation code and tests
library(readr)
library(data.table)
library(testthat)

# Function to create test data files
write_test_file <- function(filename, var_rates, suppressed_rates) {
  test_data <- data.frame(
    VAR_MUTRATE = var_rates,
    SUPRESSED_RATE = suppressed_rates
  )
  write.table(test_data, filename, sep = "\t", row.names = FALSE, quote = FALSE)
}

# Create test files
# Case 1: Simple case with known values
write_test_file("test1_time_calc.txt", 
                c(0.1, 0.2),           # Sum = 0.3, Tv = 1/0.3
                c(0.05, 0.1))          # Sum = 0.15, Ts = 1/0.15

# Case 2: With NA values
write_test_file("test2_time_calc.txt",
                c(0.1, NA, 0.2),
                c(0.05, NA, 0.1))

# Case 3: With added variants
write_test_file("test3_with_added_variants_time_calc.txt",
                c(0.2, 0.3),
                c(0.1, 0.15))

# Original calculation code
results <- data.frame(
  Patient = character(),
  Type = character(),
  Measure = character(),
  Value = numeric(),
  stringsAsFactors = FALSE
)

# Get list of all time_calc.txt files
files <- list.files(pattern = ".*time_calc\\.txt$")

# Process each file
for(file in files) {
  # Extract patient ID from filename - FIXED pattern matching
  patient <- sub("_with_added_variants_time_calc.txt", "", file)
  patient <- sub("_time_calc.txt", "", patient)
  
  # Read data
  data <- read_delim(file, delim = "\t")
  
  # Calculate Ts and Tv
  Tv <- 1 / sum(data$VAR_MUTRATE, na.rm = TRUE)
  Ts <- 1 / sum(data$SUPRESSED_RATE, na.rm = TRUE)
  
  # Calculate time gained
  time_gained <- ((Ts / Tv) - 1) * 100
  
  # Type is "Observed" for regular files and "All Variants" for files with added variants
  type <- if(grepl("with_added_variants", file)) "All Variants" else "Observed"
  
  # Add results to data frame
  results <- rbind(results, 
                  data.frame(Patient = patient,
                            Type = type,
                            Measure = "Tv",
                            Value = Tv),
                  data.frame(Patient = patient,
                            Type = type,
                            Measure = "Ts",
                            Value = Ts),
                  data.frame(Patient = patient,
                            Type = type,
                            Measure = "TimeGained",
                            Value = time_gained))
}

# Write results to TSV file
write.table(results, 
            "time_calculations_summary.tsv", 
            sep = "\t", 
            row.names = FALSE, 
            quote = FALSE)

# Test the results
test_that("Time calculations are correct", {
  # Load results
  results <- read.table("time_calculations_summary.tsv", header = TRUE, sep = "\t")
  
  # Test Case 1: Simple case
  test1_results <- subset(results, Patient == "test1")
  
  # Calculate expected values for test1
  expected_tv <- 1/0.3
  expected_ts <- 1/0.15
  expected_time_gained <- ((expected_ts/expected_tv) - 1) * 100
  
  expect_equal(subset(test1_results, Measure == "Tv")$Value, expected_tv, 
               tolerance = 1e-6)
  expect_equal(subset(test1_results, Measure == "Ts")$Value, expected_ts, 
               tolerance = 1e-6)
  expect_equal(subset(test1_results, Measure == "TimeGained")$Value, 
               expected_time_gained, tolerance = 1e-6)
  
  # Test Case 2: NA handling
  test2_results <- subset(results, Patient == "test2")
  # Should have same results as test1 since na.rm=TRUE
  expect_equal(subset(test2_results, Measure == "Tv")$Value, expected_tv, 
               tolerance = 1e-6)
  
  # Test Case 3: Type field
  test3_results <- subset(results, Patient == "test3")
  print("Test 3 Results:") # Debug print
  print(test3_results)    # Debug print
  expect_true(any(test3_results$Type == "All Variants"))
  
  # Test output format
  expect_true(all(c("Patient", "Type", "Measure", "Value") %in% names(results)))
  expect_true(all(results$Measure %in% c("Tv", "Ts", "TimeGained")))
  expect_true(all(results$Type %in% c("Observed", "All Variants")))
})

# Add additional test for expected number of rows
test_that("Output has correct number of rows", {
  results <- read.table("time_calculations_summary.tsv", header = TRUE, sep = "\t")
  # Each file should produce 3 rows (Tv, Ts, TimeGained)
  expect_equal(nrow(results), length(files) * 3)
})

# Clean up test files
file.remove("test1_time_calc.txt", 
            "test2_time_calc.txt", 
            "test3_with_added_variants_time_calc.txt",
            "time_calculations_summary.tsv")

# Print success message
cat("All tests completed. Check test results above for any failures.\n")